@startuml
start
:д1.инициализация;
if (д2.залогинен?) then (да)
    :д3.успешный логин;
else (нет)
    :д4.остановка;
    stop
endif
:д5.cбор резюме;
while (Остались резюме необработанные?) is (Да)
  :Д6. В новом окне открыть резюме;

endwhile (Нет)
:д999.конец;
end
@enduml